# Generated by Django 5.2.4 on 2025-07-31 17:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Vanguard assets'),
            preserve_default=False,
        ),
    ]
