# Generated by Django 5.2.4 on 2025-07-31 19:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_financialaccount_total_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='self_managed_accounts',
            field=models.DecimalField(decimal_places=2, default=233, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Self-managed accounts'),
            preserve_default=False,
        ),
    ]
