# Generated by Django 5.2.4 on 2025-07-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_financialaccount_total_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='self_managed_accounts',
        ),
    ]
